---
- name: Copy the Infra creation scripts
  hosts: ec2
  tasks:
      - name: copying script files to remote host
        become: true
        copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
        with_items: 
            - { src: 'install_mediawiki.sh',  dest: 'install_mediawiki.sh', mode: +x}
      - name: Executing the scripts
        become: true
        command: /tmp/install_dependencies_aws.sh