---
- hosts: ec2
  gather_facts: false
  tasks:
    - name: sudo apt update
      become: true
      apt:
              update_cache: yes

    - name: Update PPA for PHP installation
      become: true
      apt_repository:
              repo: ppa:ondrej/php
    - name: Installing dependency packages
      become: true
      apt: name={{ item }} state=present
      with_items:
              - apache2
              - mysql-server
              - php8.0
              - libapache2-mod-php8.0
              - php8.0-mysql
              - php8.0-mcrypt
              - php8.0-fpm
              - php8.0-mbstring
              - php8.0-apcu
              - php-xml
              - php-intl
    - name: Restarting apache2 service
      become: true
      service:
              name: apache2
              state: restarted
    - name: Downloading mediawiki source code
      become: true
      unarchive:
              src: https://releases.wikimedia.org/mediawiki/1.35/mediawiki-1.35.2.tar.gz
              dest: .
              remote_src: yes
    - name: Moving files
      become: true
      shell: |
              mv mediawiki-1.35.2 /var/lib/wiki
              ln -s /var/lib/wiki /var/www/html/wiki

    - name: Restarting apache2 service
      become: true
      service:
              name: apache2
              state: restarted

